import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import CocktailList from "@/components/CocktailList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CocktailCode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <main className={styles.Home}>
        <div className={styles.Home__Hero}>
          <div className={styles.Home__Text}>
          <h1>Scopri le ultime sui <b>Cocktail</b> più freschi!</h1>

          </div>
          
        </div>
        <div className={styles.Hero__Components}>
         <CocktailList/>
        </div>
      </main>
    </>
  );
}
